# Generated by Django 5.1.1 on 2025-06-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=400)),
                ('status', models.CharField(choices=[(1, 'In Progress'), (2, 'In Review'), (3, 'Completed')], default=1, max_length=50)),
                ('upvote', models.IntegerField(default=0)),
            ],
        ),
    ]
